/**
 * xcode init — scaffold .xcode/{scenarios,traces}/ in the current project.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function initCommand(opts: { force?: boolean }) {
  const root = process.cwd();
  const dotDir = join(root, ".xcode");
  if (existsSync(dotDir) && !opts.force) {
    console.log(`[xcode] .xcode/ already exists at ${dotDir} — pass --force to overwrite`);
    return;
  }
  mkdirSync(join(dotDir, "scenarios"), { recursive: true });
  mkdirSync(join(dotDir, "traces"), { recursive: true });
  // .gitignore for local traces
  const gitignorePath = join(dotDir, "traces", ".gitignore");
  if (!existsSync(gitignorePath)) {
    writeFileSync(
      gitignorePath,
      "# Local trace copies — do not commit\n*\n!.gitignore\n",
      "utf8"
    );
  }
  // README.md describing the layout
  const readmePath = join(dotDir, "README.md");
  if (!existsSync(readmePath)) {
    writeFileSync(
      readmePath,
      `# .xcode/

Local working directory for xcode scenarios and traces.

- \`scenarios/<name>.py\` — scenario scripts (Python) auto-generated by \`xcode gen-scenario\`
- \`traces/<name>.json\` — last successful trace per scenario (gitignored)
`,
      "utf8"
    );
  }
  console.log(`[xcode] initialized .xcode/ at ${dotDir}`);
}
