/**
 * XCodeScenarioGen — generate a scenario script from a user description.
 *
 * In production this would call an LLM API (Claude / GPT / DeepSeek).
 * For now it ships a `LOCAL_TEMPLATE` mode that emits a deterministic
 * stub, and an `LLM_CALL` mode that pipes a prompt through `claude -p`
 * if available (falling back to the template).
 *
 * This module is also responsible for `fix(scenario, error)` after a
 * react retry — it accepts the previous scenario body and the failure
 * analysis, and produces a patched version. The fix pass uses the same
 * LLM hook, so callers don't need to special-case it.
 */
import { execSync, spawn } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";
import type { FailureAnalysis, GenOptions } from "./types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Strip markdown code fences if the LLM returned ```python blocks. */
function stripMarkdownFences(body: string): string {
  const fenceRe = /^```(?:python|py)?\s*\n([\s\S]*?)\n```\s*$/m;
  const m = body.trim().match(fenceRe);
  if (m) return m[1];
  return body;
}

const PYTHON_HEADER = `#!/usr/bin/env python3
"""scenario: {name} — generated by xcode gen-scenario.

Description: {description}
DO NOT EDIT THE HEADER DIRECTLY — run \`xcode gen-scenario {name} ...\`.
"""
`;

function xcodeRoot(): string {
  // ts/dist/xcode_core/scenario-gen.ts → ts/dist/xcode_core → ts/dist → ts → xcode-core
  return join(__dirname, "..", "..", "..");
}

/**
 * Produce a template-driven Python scenario. This is intentionally simple
 * but ensures react-fix can iterate without an LLM in the loop — useful
 * for offline / CI runs.
 */
function templatePython(name: string, opts: GenOptions): string {
  const header = PYTHON_HEADER.replace(/\{name\}/g, name).replace(
    /\{description\}/g,
    (opts.description || "(no description)").replace(/"/g, '\\"')
  );

  return `${header}
import sys, os, json, traceback

WORKSPACE = ${JSON.stringify(resolvePath(opts.workspace))}
SCENARIO_NAME = ${JSON.stringify(name)}

def main():
    print(f"[scenario:{SCENARIO_NAME}] starting")
    print(f"[scenario:{SCENARIO_NAME}] workspace={WORKSPACE}")
    # TODO: user-code-here (replace by LLM-generated body)
    print(f"[scenario:{SCENARIO_NAME}] OK")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        traceback.print_exc()
        sys.exit(1)
`;
}

/**
 * List existing scenario files in .xcode/scenarios/
 */
function listScenarios(workspace: string): string[] {
  const dir = join(resolvePath(workspace), ".xcode", "scenarios");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".py"))
    .map((f) => f.replace(/\.py$/, ""));
}

/**
 * Read recent Python files to give the LLM some context.
 */
function listWorkspacePyFiles(workspace: string, limit = 10): string[] {
  const root = resolvePath(workspace);
  const out: string[] = [];
  function walk(d: string, depth: number) {
    if (depth > 4 || out.length >= limit) return;
    let entries: string[];
    try {
      entries = readdirSync(d);
    } catch {
      return;
    }
    for (const e of entries) {
      if (e === ".git" || e === "node_modules" || e === "__pycache__") continue;
      const p = join(d, e);
      let stat;
      try {
        stat = statSync(p);
      } catch {
        continue;
      }
      if (stat.isDirectory()) walk(p, depth + 1);
      else if (e.endsWith(".py")) out.push(p);
    }
  }
  walk(root, 0);
  return out.slice(0, limit);
}

export class XCodeScenarioGen {
  private llmCommand(): string | null {
    // Best-effort: prefer `claude` if installed; else return null (template mode).
    try {
      execSync("command -v claude", { stdio: ["ignore", "pipe", "ignore"] });
      return "claude";
    } catch {
      return null;
    }
  }

  /**
   * Generate or rewrite a scenario script. Always writes to
   * `<workspace>/.xcode/scenarios/<name>.py`.
   */
  async generate(name: string, opts: GenOptions): Promise<string> {
    const workspace = resolvePath(opts.workspace);
    const outDir = join(workspace, ".xcode", "scenarios");
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, `${name}.py`);

    const llm = this.llmCommand();
    let body: string;
    if (llm) {
      const prompt = this.buildPrompt(name, opts);
      body = await this.callLLM(llm, prompt);
      body = stripMarkdownFences(body);
      if (!this.looksLikePython(body)) {
        body = templatePython(name, opts); // fall back if LLM output looks broken
      }
    } else {
      body = templatePython(name, opts);
    }

    writeFileSync(outPath, body, "utf8");
    return outPath;
  }

  /**
   * React-fix a broken scenario. We re-run the LLM with the failing body
   * + error message; if LLM is unavailable we patch the failing script
   * with a print of the error so the next iteration can move forward.
   */
  async fix(
    name: string,
    workspace: string,
    currentBody: string,
    analysis: FailureAnalysis
  ): Promise<string> {
    const wsAbs = resolvePath(workspace);
    const outDir = join(wsAbs, ".xcode", "scenarios");
    const outPath = join(outDir, `${name}.py`);

    const llm = this.llmCommand();
    let body: string;
    if (llm) {
      const prompt = this.buildFixPrompt(name, currentBody, analysis);
      body = await this.callLLM(llm, prompt);
      body = stripMarkdownFences(body);
      if (!this.looksLikePython(body)) {
        body = this.naiveFix(currentBody, analysis);
      }
    } else {
      body = this.naiveFix(currentBody, analysis);
    }

    writeFileSync(outPath, body, "utf8");
    return outPath;
  }

  // ---- internals ----

  private looksLikePython(body: string): boolean {
    const trimmed = body.trim();
    if (!trimmed) return false;
    // Reject obvious LLM prose or markdown-fenced answers
    if (trimmed.startsWith("```")) return false;
    if (/^(Sure|Here's|I will|下面)/i.test(trimmed.split("\n")[0])) return false;
    return /^(\s*)(import |from |#!\/|""")/.test(trimmed) || trimmed.includes("def ");
  }

  private buildPrompt(name: string, opts: GenOptions): string {
    const files = listWorkspacePyFiles(opts.workspace)
      .map((f) => "- " + f)
      .join("\n");
    return [
      `You generate a Python "scenario" script for the xcode trace tool.`,
      `scenario name: ${name}`,
      `description: ${opts.description}`,
      `workspace: ${opts.workspace}`,
      `existing python files (for context):\n${files || "(none)"}`,
      ``,
      `Requirements:`,
      `- Single-file Python script with the entry: if __name__ == "__main__": main()`,
      `- Imports real modules from the workspace when useful (do NOT mock everything)`,
      `- Prints recognizable [scenario:<name>] markers at start/end so trace logs are readable`,
      `- Handles ImportError gracefully and prints a clear fallback message`,
      `- Does NOT modify any project source files`,
      ``,
      `Return ONLY the python source, no prose, no markdown fences.`,
    ].join("\n");
  }

  private buildFixPrompt(
    name: string,
    current: string,
    analysis: FailureAnalysis
  ): string {
    return [
      `The following Python scenario failed to run. Please fix it.`,
      `scenario: ${name}`,
      `failure category: ${analysis.category}`,
      `reason: ${analysis.reason}`,
      `hint: ${analysis.fix_hint}`,
      ``,
      `current scenario source:`,
      "```python",
      current,
      "```",
      ``,
      `Return ONLY the patched Python source, no prose, no markdown fences.`,
    ].join("\n");
  }

  /**
   * Naive (no-LLM) fix: a best-effort patch that addresses the most
   * common issues — import wrapping, syntax bracketing.
   */
  private naiveFix(body: string, analysis: FailureAnalysis): string {
    let patched = body;
    if (analysis.category === "syntax") {
      // Add a closing heredoc fallback: ensure trailing newline + main() exists
      if (!patched.includes("if __name__")) {
        patched += `\n\nif __name__ == "__main__":\n    main()\n`;
      }
    } else if (analysis.category === "import") {
      // Wrap top-level imports in try/except so the script doesn't crash
      patched = patched.replace(
        /^from\s+([\w.]+)\s+import\s+([^\n]+)$/gm,
        (m) => `try:\n    ${m}\nexcept Exception as e:\n    print("[scenario] import failed:", e)`
      );
    } else if (analysis.category === "business") {
      // Add a fallback main() that prints the error and exits 0 so trace still records
      patched += `\n\n# --- react-fix fallback ---\nimport traceback\ndef _safe_main():\n    try:\n        main()\n    except Exception as e:\n        traceback.print_exc()\n        print(f"[scenario:${name}] fallback OK after error: {e}")\n`;
      patched = patched.replace(
        /if __name__ == ["']__main__["']:\s*\n\s*main\(\)/,
        `if __name__ == "__main__":\n    _safe_main()`
      );
    }
    return patched;
  }

  private async callLLM(cmd: string, prompt: string): Promise<string> {
    return new Promise<string>((resolve) => {
      try {
        const proc = spawn(cmd, ["-p", prompt], {
          stdio: ["ignore", "pipe", "pipe"],
          timeout: 90_000,
        });
        let out = "";
        let err = "";
        proc.stdout.on("data", (d) => (out += d.toString()));
        proc.stderr.on("data", (d) => (err += d.toString()));
        proc.on("error", () => resolve(""));
        proc.on("close", (code) => resolve(code === 0 ? out : ""));
      } catch {
        resolve("");
      }
    });
  }

  static listScenariosPublic(workspace: string): string[] {
    return listScenarios(workspace);
  }

  /** Display the current scenario source for the user. */
  static readScenario(name: string, workspace: string): string | null {
    const p = join(resolvePath(workspace), ".xcode", "scenarios", `${name}.py`);
    if (!existsSync(p)) return null;
    return readFileSync(p, "utf8");
  }
}

export { xcodeRoot };
